create table if not exists public.parari_english_dictionary (
  id bigint generated by default as identity primary key,
  word text not null,
  normalized_word text generated always as (lower(btrim(word))) stored,
  lemma text not null,
  pos text not null default 'unknown',
  form_type text not null default 'base',
  sense_id text not null default '1',
  meaning_ja text not null default '',
  eiken_level text,
  eiken_levels text[] not null default '{}'::text[],
  parari_level text,
  importance smallint not null default 1,
  entry_kind text not null default 'word',
  source text not null default 'dictionary',
  category text,
  note text,
  note2 text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid,
  constraint parari_english_dictionary_importance_check check (importance between 1 and 3),
  constraint parari_english_dictionary_eiken_check check (
    eiken_level is null or eiken_level in ('5','4','3','pre2','2','pre1','1')
  )
);

create unique index if not exists parari_english_dictionary_identity_idx
on public.parari_english_dictionary
(normalized_word, lower(lemma), pos, form_type, sense_id);

create index if not exists parari_english_dictionary_lemma_idx
on public.parari_english_dictionary(lower(lemma));

create index if not exists parari_english_dictionary_eiken_idx
on public.parari_english_dictionary(eiken_level)
where active = true;

alter table public.parari_english_dictionary enable row level security;
revoke all on table public.parari_english_dictionary from anon, authenticated;
grant select, insert, update, delete on table public.parari_english_dictionary to service_role;
grant usage, select on sequence public.parari_english_dictionary_id_seq to service_role;

create table if not exists public.parari_english_dictionary_history (
  id bigint generated by default as identity primary key,
  dictionary_entry_id bigint,
  action text not null check (action in ('create','update','delete','import')),
  before_value jsonb,
  after_value jsonb,
  changed_by uuid,
  changed_at timestamptz not null default now()
);

create index if not exists parari_english_dictionary_history_entry_idx
on public.parari_english_dictionary_history(dictionary_entry_id, changed_at desc);

alter table public.parari_english_dictionary_history enable row level security;
revoke all on table public.parari_english_dictionary_history from anon, authenticated;
grant select, insert on table public.parari_english_dictionary_history to service_role;
grant usage, select on sequence public.parari_english_dictionary_history_id_seq to service_role;
